cvbuilder/urls.py
from django.urls import path
from . import views

app_name = 'cvbuilder'

urlpatterns = [
    path('', views.MainPage.as_view(), name='MainPage'),
    path('preview/', views.ResumePreview.as_view(), name='ResumePreview'),

    path('create_experience/', views.CreateExperience.as_view(), name='CreateExperience'),
    path('update_experience/<str:pk>', views.UpdateExperience.as_view(), name='UpdateExperience'),
    path('delete_experience/<str:pk>', views.DeleteExperience.as_view(), name='DeleteExperience'),
    path('save_experience_order/', views.SaveExperienceOrdering.as_view(), name='SaveExperienceOrdering'),

    path('create_skill/', views.CreateSkill.as_view(), name='CreateSkill'),
    path('delete_skill/<str:pk>', views.DeleteSkill.as_view(), name='DeleteSkill'),
    path('save_skill_order/', views.SaveSkillsOrder.as_view(), name='SaveSkillsOrder'),

    path('create_education/', views.CreateEducation.as_view(), name='CreateEducation'),
    path('update_education/<str:pk>/', views.UpdateEducation.as_view(), name='UpdateEducation'),
    path('delete_education/<str:pk>/', views.DeleteEducation.as_view(), name='DeleteEducation'),
    path('save_education_order/', views.SaveEducationOrder.as_view(), name='SaveEducationOrder'),

    path('create_language/', views.CreateLanguage.as_view(), name='CreateLanguage'),
    path('update_language/<str:pk>/', views.UpdateLanguage.as_view(), name='UpdateLanguage'),
    path('delete_language/<str:pk>/', views.DeleteLanguage.as_view(), name='DeleteLanguage'),
    path('save_language_order/', views.SaveLanguageOrder.as_view(), name='SaveLanguageOrder'),

    path('create_achievement/', views.CreateAchievement.as_view(), name='CreateAchievement'),
    path('update_achivement/<str:pk>/', views.UpdateAchievement.as_view(), name='UpdateAchievement'),
    path('delete_achievement/<str:pk>/', views.DeleteAchievement.as_view(), name='DeleteAchievement'),
    path('save_achievement_order/', views.SaveAchievementOrder.as_view(), name='SaveAchievementOrder'),

    path('create_publication/', views.CreatePublication.as_view(), name='CreatePublication'),
    path('update_publication/<str:pk>/', views.UpdatePublication.as_view(), name='UpdatePublication'),
    path('delete_publication/<str:pk>/', views.DeletePublication.as_view(), name='DeletePublication'),
    path('save_publication_order/', views.SavePublicationOrder.as_view(), name='SavePublicationOrder'),

    path('share/<str:code>', views.SharedResumePreview.as_view(), name='SharedResumePreview'),
    path('download_pdf/', views.PDFView, name='pdf')
]

jobapp/urls.py
from django.urls import path
from jobapp import views

app_name = "jobapp"


urlpatterns = [

    path('', views.home_view, name='home'),
    path('jobs/', views.job_list_View, name='job-list'),
    path('job/create/', views.create_job_View, name='create-job'),
    path('job/<int:id>/', views.single_job_view, name='single-job'),
    path('apply-job/<int:id>/', views.apply_job_view, name='apply-job'),
    path('bookmark-job/<int:id>/', views.job_bookmark_view, name='bookmark-job'),
    path('about/', views.single_job_view, name='about'),
    path('contact/', views.single_job_view, name='contact'),
    path('result/', views.search_result_view, name='search_result'),
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('dashboard/employer/job/<int:id>/applicants/', views.all_applicants_view, name='applicants'),
    path('dashboard/employer/job/edit/<int:id>', views.job_edit_view, name='edit-job'),
    path('dashboard/employer/applicant/<int:id>/<int:idjob>', views.applicant_details_view, name='applicant-details'),
    path('dashboard/employer/close/<int:id>/', views.make_complete_job_view, name='complete'),
    path('dashboard/employer/delete/<int:id>/', views.delete_job_view, name='delete'),
    path('dashboard/employee/delete-bookmark/<int:id>/', views.delete_bookmark_view, name='delete-bookmark'),


]

project-config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from .views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/',user_logIn,name="login"),
    path('employee/register',employee_registration, name='employee-registration'),
    path('employer/register',employer_registration, name='employer-registration'),
    path('profile/edit/<int:id>/', employee_edit_profile, name='edit-profile'),
    path('logout/', user_logOut, name='logout'),
    path('', include('jobapp.urls')),
    path('cvbuilder/', include('cvbuilder.urls')),
    
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cvbuilder/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser
import random
import string

from .managers import CustomUserManager

JOB_TYPE = (
    ('M', "Male"),
    ('F', "Female"),

)

ROLE = (
    ('employer', "Employer"),
    ('employee', "Employee"),
)

class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, blank=False, error_messages={'unique': "A user with that email already exists.",})
    role = models.CharField(choices=ROLE,  max_length=10)
    gender = models.CharField(choices=JOB_TYPE, max_length=1)


    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    def get_full_name(self):
        return self.first_name+ ' ' + self.last_name
    objects = CustomUserManager()

class Template(models.Model):
    name = models.CharField(max_length=65)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Template'
        verbose_name_plural = 'Templates'


class Resume(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, primary_key=True)
    image = models.ImageField(upload_to='cv_images', null=True, blank=True)
    name = models.CharField(max_length=255, blank=True, null=True,verbose_name='Name-Surname')
    description = models.CharField(max_length=255, blank=True)
    telephone = models.CharField(max_length=255, blank=True)
    email = models.EmailField(blank=True)
    career_summary = models.TextField(blank=True, verbose_name='Career Summary')
    linkedin = models.CharField(max_length=255, blank=True)
    github = models.CharField(max_length=255, blank=True)
    website = models.CharField(max_length=255, blank=True)
    template = models.ForeignKey(Template, on_delete=models.CASCADE, null=True, blank=True)
    code = models.CharField(max_length=8, default="", blank=True, unique=True)

    def __str__(self):
        return '%s - %s' % (self.name, self.description)

    def save(self, *args, **kwargs):
        if self.code == "": self.code = self.get_resume_code()
        super().save(*args, **kwargs)

    def get_resume_code(self):
        length = 8
        while True:
            code = ''.join(random.choices(string.ascii_uppercase, k=length))
            if Resume.objects.filter(code=code).count() == 0:
                break
        return code

    class Meta:
        verbose_name = 'Resume'
        verbose_name_plural = 'Resumes'


class Experience(models.Model):
    title = models.CharField(max_length=255)
    company = models.CharField(max_length=255)
    duration = models.CharField(max_length=255)
    text = models.TextField(blank=True)
    tech = models.TextField(blank=True)
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE, related_name='experiences')
    order = models.IntegerField(blank=False, default=100_000)

    def tech_as_list(self):
        tech_list = ""
        if not self.tech == "":
            tech_list = self.tech.replace(", ", ",").split(',')
            tech_list = [x[0].upper() + x[1:] for x in tech_list]
        return tech_list

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Experience'
        verbose_name_plural = 'Experiences'


class Skill(models.Model):
    title = models.CharField(max_length=38)
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE, related_name='skills')
    order = models.IntegerField(blank=False, default=100_000)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Skill'
        verbose_name_plural = 'Skills'


class Education(models.Model):
    title = models.CharField(max_length=255)
    description = models.CharField(max_length=255, verbose_name='Department')
    duration = models.CharField(max_length=255)
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE, related_name='educations')
    order = models.IntegerField(blank=False, default=100_000)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Education'
        verbose_name_plural = 'Educations'


class Achievement(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE, related_name='achievements')
    order = models.IntegerField(blank=False, default=100_000)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Achievement'
        verbose_name_plural = 'Achievements'


class Language(models.Model):
    title = models.CharField(max_length=255)
    level = models.CharField(max_length=255)
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE, related_name='languages')
    order = models.IntegerField(blank=False, default=100_000)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Language'
        verbose_name_plural = 'Languages'


class Publication(models.Model):
    title = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE, related_name='publications')
    order = models.IntegerField(blank=False, default=100_000)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Publication'
        verbose_name_plural = 'Publications'

cvbuilder/forms.py
from .models import Experience, Resume
from django import forms
from .widgets import CustomClearableFileInput
from ckeditor.widgets import CKEditorWidget
from .models import User
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm


class ResumeForm(forms.ModelForm):
    image = forms.ImageField(required=False, widget=CustomClearableFileInput())

    class Meta:
        model = Resume
        fields = ['image', 'name', 'email', 'telephone', 'linkedin', 'github',
                  'website', 'description', 'career_summary', 'template']
        widgets = {
            'career_summary': CKEditorWidget(config_name='CVBuilder_Config')
        }


class ExperienceForm(forms.ModelForm):
    class Meta:
        model = Experience
        fields = ['title', 'company', 'duration', 'text', 'tech']
        widgets = {
            'text': CKEditorWidget(config_name='CVBuilder_Config'),
        }

cvbuilder/templates/cvbuilder/4_education.html
{% load static %}
{% if educations %}

 <div class="card">
    <!-- Header -->
    <div class="card-header bg-dark text-center section-hero" style="background-image: url('{% static 'images/hero_1.jpg' %}');height:fit-content;min-height:fit-content" id="heading4">
        <h3 class="mb-0">
            <button class="btn btn-link text-light" data-toggle="collapse" data-target="#collapse4" aria-expanded="true" aria-controls="collapse4">
                <span style="font-size:1.3em;">
                    <i class="fas fa-school mr-2"></i> Education
                </span>
            </button>
        </h3>
    </div>

    <div id="collapse4" class="collapse" aria-labelledby="heading4" data-parent="#accordion">

        <!-- Card Body -->
        <div class="card-body">
            
            <table class="table table-responsive-sm mb-0">
                
                <thead class="table-dark">
                    <tr class="text-center">
                        <th scope="col"></th>
                        <th scope="col">Title</th>
                        <th scope="col">Description</th>
                        <th scope="col">Duration</th>
                        <th scope="col"></th>
                        <th scope="col"></th>
                    </tr>
                </thead>

                <form id="educationOrderingForm" method="post" action="{% url 'cvbuilder:SaveEducationOrder' %}"> {% csrf_token %}
                    
                    <tbody id="educations" class="text-center">

                        {% for education in educations %}

                            <tr data-lookup="{{ education.id }}">
                                <td><span class="handle_educations handle"></span></td>                
                                <td>{{ education.title }}</td>
                                <td>{{ education.description }}</td>
                                <td>{{ education.duration }}</td>
                                <td>
                                    <a href="{% url 'cvbuilder:UpdateEducation' education.id %}">
                                        <div class="text-center text-success">
                                            <i class="far fa-edit"></i>
                                        </div>
                                    </a>
                                </td>
                                <td>
                                    <a href="{% url 'cvbuilder:DeleteEducation' education.id %}">
                                        <div class="text-center text-danger">
                                            <i class="far fa-trash-alt"></i>
                                        </div>
                                    </a>
                                </td>
                            </tr>

                        {% endfor %}

                    </tbody>

                    <input type="hidden" id="educationOrderingInput" name="ordering">
                </form>

            </table>
        </div>
    </div>
</div>

{% endif %}

cvbuilder/templates/cvbuilder/5_language.html
{% load static %}
{% if languages %}


 <div class="card">
    <!-- Header -->
    <div class="card-header bg-dark text-center section-hero" style="background-image: url('{% static 'images/hero_1.jpg' %}');height:fit-content;min-height:fit-content" id="heading5">
        <h3 class="mb-0">
            <button class="btn btn-link text-light" data-toggle="collapse" data-target="#collapse5" aria-expanded="true" aria-controls="collapse5">
                <span style="font-size:1.3em;">
                    <i class="fas fa-globe-europe mr-1"></i> Languages
                </span>
            </button>
        </h3>
    </div>

    <div id="collapse5" class="collapse" aria-labelledby="heading5" data-parent="#accordion">
        <!-- Card Body -->
        <div class="card-body">
           

            <table class="table table-responsive-sm mb-0">
                
                <thead class="table-dark">
                    <tr class="text-center">
                        <th scope="col"></th>
                        <th scope="col">Language</th>
                        <th scope="col">Level</th>
                        <th scope="col"></th>
                        <th scope="col"></th>
                    </tr>
                </thead>

                <form id="languageOrderingForm" method="post" action="{% url 'cvbuilder:SaveLanguageOrder' %}"> {% csrf_token %}
                    
                    <tbody class="text-center" id="languages">

                        {% for language in languages %}

                            <tr data-lookup="{{ language.id }}">
                                <td><span class="handle_languages handle"></span></td>                
                                <td>{{ language.title }}</td>
                                <td>{{ language.level }}</td>
                                <td>
                                    <a href="{% url 'cvbuilder:UpdateLanguage' language.id %}">
                                        <div class="text-center text-success">
                                            <i class="far fa-edit"></i>
                                        </div>
                                    </a>
                                </td>
                                <td>
                                    <a href="{% url 'cvbuilder:DeleteLanguage' language.id %}">
                                        <div class="text-center text-danger">
                                            <i class="far fa-trash-alt"></i>
                                        </div>
                                    </a>
                                </td>
                            </tr>

                        {% endfor %}

                    </tbody>

                    <input type="hidden" id="languageOrderingInput" name="ordering">
                </form>

            </table>


        </div>
    </div>
</div>

{% endif %}

cvbuilder/templates/cvbuilder/6_achievement.html
{% load static %}
{% if achievements %}

 <div class="card">
    <!-- Header -->
    <div class="card-header bg-dark text-center section-hero" style="background-image: url('{% static 'images/hero_1.jpg' %}');height:fit-content;min-height:fit-content" id="heading6">
        <h3 class="mb-0">
            <button class="btn btn-link text-light" data-toggle="collapse" data-target="#collapse6" aria-expanded="true" aria-controls="collapse6">
                <span style="font-size:1.3em;">
                    <i class="fas fa-trophy mr-1"></i> Achievements
                </span>
            </button>
        </h3>
    </div>

    <div id="collapse6" class="collapse" aria-labelledby="heading6" data-parent="#accordion">
        <!-- Card Body -->
        <div class="card-body">
           

            <table class="table table-responsive-sm mb-0">
                
                <thead class="table-dark">
                    <tr class="text-center">
                        <th scope="col"></th>
                        <th scope="col">Name</th>
                        <th scope="col">Description</th>
                        <th scope="col"></th>
                        <th scope="col"></th>
                    </tr>
                </thead>

                <form id="achievementOrderingForm" method="post" action="{% url 'cvbuilder:SaveAchievementOrder' %}"> {% csrf_token %}
                    
                    <tbody class="text-center" id="achievements">

                        {% for achievement in achievements %}

                            <tr data-lookup="{{ achievement.id }}">
                                <td><span class="handle_languages handle"></span></td>                
                                <td>{{ achievement.title }}</td>
                                <td>{{ achievement.description }}</td>
                                <td>
                                    <a href="{% url 'cvbuilder:UpdateAchievement' achievement.id %}">
                                        <div class="text-center text-success">
                                            <i class="far fa-edit"></i>
                                        </div>
                                    </a>
                                </td>
                                <td>
                                    <a href="{% url 'cvbuilder:DeleteAchievement' achievement.id %}">
                                        <div class="text-center text-danger">
                                            <i class="far fa-trash-alt"></i>
                                        </div>
                                    </a>
                                </td>
                            </tr>

                        {% endfor %}

                    </tbody>

                    <input type="hidden" id="achievementOrderingInput" name="ordering">
                </form>

            </table>


        </div>
    </div>
</div>

{% endif %}

cvbuilder/templates/cvbuilder/7_script.html
{% load static %}

<script src="{% static 'cvbuilder/Sortable.min.js' %}"></script>

<script>

    // Template
    $('#id_template').addClass('form-control');

    // Name 
    $('#id_name').addClass('form-control');
    $('#id_name').attr("placeholder", "Name - Surname");
    // Email
    $('#id_email').addClass('form-control');
    $('#id_email').attr("placeholder", "Email Address");
    // Phone Number
    $('#id_telephone').addClass('form-control');
    $('#id_telephone').attr("placeholder", "Phone Number");
    // Linkedin Address
    $('#id_linkedin').addClass('form-control');
    $('#id_linkedin').attr("placeholder", "LinkedIn Address");
    // Github
    $('#id_github').addClass('form-control');
    $('#id_github').attr("placeholder", "Github Address");
    // Personal Website
    $('#id_website').addClass('form-control');
    $('#id_website').attr("placeholder", "Personal Website");
    // Primary Title
    $('#id_description').addClass('form-control');
    $('#id_description').attr("placeholder", "Primary Title");
    // Career Summary
    $('#id_career_summary').addClass('form-control');
    $('#id_career_summary').attr("placeholder", "Career Summary");
    // Default option
    $("option:contains('---------')").text("Select Resume Template");

// ---- Sortable for Experiences - if exists

    if($('#experiences').length){
        const groups = document.getElementById('experiences');
        let sortable = Sortable.create(groups, {
            handle: '.handle_experiences',
            onEnd: () => {
                saveExperienceOrder();
            }
        });
    }

    function saveExperienceOrder() {
        const rows = $('#experiences > tr');
        let ids = [];
        for (let row of rows) {
            ids.push(row.dataset.lookup);
        }
        $('#orderingInput').val(ids.join(','));
        $('#orderingForm').submit();
    }

// ---- Sortable for Skills - if exists

    if($('#skills').length){
        const skills = document.getElementById('skills');
        let skills_sortable = Sortable.create(skills, {
            onEnd: () => {
                saveSkillsOrder();
            }
        });
    }

    function saveSkillsOrder(){
        var skill_rows = $('#skills > li')
        var skill_ids = [];
        for(var row of skill_rows){
            skill_ids.push(row.dataset.lookup);
        };
        $('#skillsOrderingInput').val(skill_ids.join(','));
        $('#skillsOrderingForm').submit();
    }

// ---- Sortable for Education - if exists

    if($('#educations').length){
        const educations = document.getElementById('educations');
        let educations_sortable = Sortable.create(educations, {
            onEnd: () => {
                saveEducationOrder();
            }
        });
    };

    function saveEducationOrder(){
        var education_rows = $('#educations > tr');
        var education_ids = [];
        for(var row of education_rows){
            education_ids.push(row.dataset.lookup);
        };
        $('#educationOrderingInput').val(education_ids.join(','));
        $('#educationOrderingForm').submit();
    }

// ---- Sortable for Language - if exists

    if($('#languages').length){
        const languages = document.getElementById('languages');
        let languages_sortable = Sortable.create(languages, {
            onEnd: () => {
                saveLanguageOrder();
            }
        });
    };

    function saveLanguageOrder(){
        var language_rows = $('#languages > tr');
        var language_ids = [];
        for(var row of language_rows){
            language_ids.push(row.dataset.lookup);
        };
        $('#languageOrderingInput').val(language_ids.join(','));
        $('#languageOrderingForm').submit();
    }

// ---- Sortable for Achievement - if exists

    if($('#achievements').length){
        const achievements = document.getElementById('achievements');
        let achievements_sortable = Sortable.create(achievements, {
            onEnd: () => {
                saveAchiementOrder();
            }
        });
    };

    function saveAchiementOrder(){
        var achievement_rows = $('#achievements > tr');
        var achievement_ids = [];
        for(var row of achievement_rows){
            achievement_ids.push(row.dataset.lookup);
        };
        $('#achievementOrderingInput').val(achievement_ids.join(','));
        $('#achievementOrderingForm').submit();
    }

// ---- Sortable for Publication - if exists

    if($('#publications').length){
        const publications = document.getElementById('publications');
        let publications_sortable = Sortable.create(publications, {
            onEnd: () => {
                savePublicationOrder();
            }
        });
    };

    function savePublicationOrder(){
        var publication_rows = $('#publications > tr');
        var publication_ids = [];
        for(var row of publication_rows){
            publication_ids.push(row.dataset.lookup);
        };
        $('#publicationOrderingInput').val(publication_ids.join(','));
        $('#publicationOrderingForm').submit();
    }

</script>

cvbuilder/templates/cvbuilder/8_cv_navbar.html
{% load static %}
{% for message in messages %}
    <div class="alert alert-info mb-0 text-center" role="alert">
        {{ message }}
    </div>
{% endfor %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark section-hero" style="background-image: url('{% static 'images/hero_1.jpg' %}');display: block;height:fit-content;min-height:fit-content">
    <button class="navbar-toggler mb-1" data-toggle="collapse" data-target="#navbarForCvBuilder">
        <span class="navbar-toggler-icon"></span>
    </button>
    <header class="site-navbar mt-3" style="position: static;margin-top: 0px !important;">
    <div class="container-fluid" style="display: block;">
      <div class="row align-items-center" style="display: flex;
      -ms-flex-wrap: wrap;
      flex-wrap: wrap;
      margin-right: -15px;
      margin-left: -15px;
      justify-content: space-between">
        <div class="site-logo" style="position: static;"><a href="{% url 'jobapp:home' %}">DJobPortal</a></div>
        <nav class="mx-auto site-navigation" style="position: static;-webkit-transform: translateX(0);
        margin-right: 0px!important;
        -ms-transform: translateX(-50%);
        transform: translateX(0%);">
          <ul class="site-menu js-clone-nav d-none d-xl-block ml-0 pl-0">
            <li><a href="{% url 'jobapp:home' %}" class="nav-link">Home</a></li>
            <li><a href="#">About</a></li>
            <li><a href="{% url 'jobapp:job-list' %}">Job Listings</a></li>
            <li><a href="#">Contact</a></li>
          </ul>
        </nav>
        <div class="right-cta-menu text-right d-flex aligin-items-center" style="position: static;">
          <div class="ml-auto">
            <div class="site-navigation fix" style="    /* -webkit-transform: translateX(-50%); */
            -ms-transform: translateX(0);
            position: static;
            transform: translateX(0)">
              <ul class="site-menu js-clone-nav d-none d-xl-block ml-0 pl-0">

                {% if user.is_authenticated and user.role == 'employer'  %}
                <a href="{% url 'jobapp:create-job' %}"
                  class="js-clone-nav pr-3 btn btn-outline-white border-width-2 d-none d-lg-inline-block"><span
                    class="mr-2 icon-add"></span>Publish Job</a>

                  
                    <li class="pr-3 has-children">
                      <a>Dashboard</a> 
                      <ul class="dropdown" style="z-index: 99999;">
                        <li><a href="{% url 'jobapp:dashboard' %}">Dashboard</a></li>
                        <li><a href="{% url 'logout' %}">Logout</a></li>
                      </ul>
                    </li>

                {% elif user.is_authenticated %}
                <li class="pr-3 has-children">
                  <a>Profile</a>
                  <ul class="dropdown" style="z-index: 99999;">
                    <li><a href="{% url 'edit-profile' request.user.id %}">Edit Settings</a></li>
                  </ul>
                </li>

                <li class="pr-3 has-children">
                  <a>Dashboard</a> 
                  <ul class="dropdown" style="z-index: 99999;">
                    <li><a href="{% url 'jobapp:dashboard' %}">Dashboard</a></li>
                    <li><a href="{% url 'logout' %}">Logout</a></li>
                  </ul>
                </li>
              
                {% else %}

                <li class="pr-3 has-children">
                  <a>Register</a>
                  <ul class="dropdown">
                    <li><a href="{% url 'employer-registration' %}">Employer</a></li>
                    <li><a href="{% url 'employee-registration' %}">Employee</a></li>
                  </ul>
                </li>

                <a href="{% url 'login' %}"
                  class="js-clone-nav btn btn-primary border-width-2 d-none d-lg-inline-block ov-fix"><span
                    class="mr-2 icon-lock_outline"></span>Log In</a>
                {% endif %}
              </ul>
            </div>

        <a href="#" class="site-menu-toggle js-menu-toggle d-inline-block d-xl-none mt-lg-2 ml-3"><span
            class="icon-menu h3 m-0 p-0 mt-2"></span></a>
      </div>
    </div>
  </header>
    <div class="navbar-collapse collapse justify-content-center" id="navbarForCvBuilder">
        <ul class="nav navbar-nav">
            <a class="btn btn-outline-light mr-1 mt-1 mb-1" href="{% url 'cvbuilder:MainPage' %}"><i class="fas fa-eye"></i> Resume Details</a>
            <a class="btn btn-light mr-1 mt-1 mb-1" href="{% url 'cvbuilder:CreateExperience' %}" id="addexp"><i class="fas fa-plus"></i> Add Experience</a>
            <a class="btn btn-outline-light mr-1 mt-1 mb-1" href="{% url 'cvbuilder:CreateSkill' %}" id="addskill"><i class="fas fa-plus"></i> Add Skill</a>
            <a class="btn btn-outline-light mr-1 mt-1 mb-1" href="{% url 'cvbuilder:CreateEducation' %}"><i class="fas fa-plus"></i> Add Education</a>
            <a class="btn btn-outline-light mr-1 mt-1 mb-1" href="{% url 'cvbuilder:CreateLanguage' %}"><i class="fas fa-plus"></i> Add Language</a>
            <a class="btn btn-outline-light mr-1 mt-1 mb-1" href="{% url 'cvbuilder:CreateAchievement' %}"><i class="fas fa-plus"></i> Add Achievement</a>
            <a class="btn btn-outline-light mr-1 mt-1 mb-1" href="{% url 'cvbuilder:CreatePublication' %}"><i class="fas fa-plus"></i> Add Publication</a>
            <a class="btn btn-outline-warning mr-1 mt-1 mb-1" href="{% url 'cvbuilder:ResumePreview' %}"><i class="fas fa-search"></i> Preview Your Resume</a>
    </div>
</nav>