cvbuilder/urls.py
from django.urls import path
from . import views

app_name = 'cvbuilder'

urlpatterns = [
    path('', views.MainPage.as_view(), name='MainPage'),
    path('preview/', views.ResumePreview.as_view(), name='ResumePreview'),

    path('create_experience/', views.CreateExperience.as_view(), name='CreateExperience'),
    path('update_experience/<str:pk>', views.UpdateExperience.as_view(), name='UpdateExperience'),
    path('delete_experience/<str:pk>', views.DeleteExperience.as_view(), name='DeleteExperience'),
    path('save_experience_order/', views.SaveExperienceOrdering.as_view(), name='SaveExperienceOrdering'),

    path('create_skill/', views.CreateSkill.as_view(), name='CreateSkill'),
    path('delete_skill/<str:pk>', views.DeleteSkill.as_view(), name='DeleteSkill'),
    path('save_skill_order/', views.SaveSkillsOrder.as_view(), name='SaveSkillsOrder'),

    path('create_education/', views.CreateEducation.as_view(), name='CreateEducation'),
    path('update_education/<str:pk>/', views.UpdateEducation.as_view(), name='UpdateEducation'),
    path('delete_education/<str:pk>/', views.DeleteEducation.as_view(), name='DeleteEducation'),
    path('save_education_order/', views.SaveEducationOrder.as_view(), name='SaveEducationOrder'),

    path('create_language/', views.CreateLanguage.as_view(), name='CreateLanguage'),
    path('update_language/<str:pk>/', views.UpdateLanguage.as_view(), name='UpdateLanguage'),
    path('delete_language/<str:pk>/', views.DeleteLanguage.as_view(), name='DeleteLanguage'),
    path('save_language_order/', views.SaveLanguageOrder.as_view(), name='SaveLanguageOrder'),

    path('create_achievement/', views.CreateAchievement.as_view(), name='CreateAchievement'),
    path('update_achivement/<str:pk>/', views.UpdateAchievement.as_view(), name='UpdateAchievement'),
    path('delete_achievement/<str:pk>/', views.DeleteAchievement.as_view(), name='DeleteAchievement'),
    path('save_achievement_order/', views.SaveAchievementOrder.as_view(), name='SaveAchievementOrder'),

    path('create_publication/', views.CreatePublication.as_view(), name='CreatePublication'),
    path('update_publication/<str:pk>/', views.UpdatePublication.as_view(), name='UpdatePublication'),
    path('delete_publication/<str:pk>/', views.DeletePublication.as_view(), name='DeletePublication'),
    path('save_publication_order/', views.SavePublicationOrder.as_view(), name='SavePublicationOrder'),

    path('share/<str:code>', views.SharedResumePreview.as_view(), name='SharedResumePreview'),
    path('download_pdf/', views.PDFView, name='pdf')
]

jobapp/urls.py
from django.urls import path
from jobapp import views

app_name = "jobapp"


urlpatterns = [

    path('', views.home_view, name='home'),
    path('jobs/', views.job_list_View, name='job-list'),
    path('job/create/', views.create_job_View, name='create-job'),
    path('job/<int:id>/', views.single_job_view, name='single-job'),
    path('apply-job/<int:id>/', views.apply_job_view, name='apply-job'),
    path('bookmark-job/<int:id>/', views.job_bookmark_view, name='bookmark-job'),
    path('about/', views.single_job_view, name='about'),
    path('contact/', views.single_job_view, name='contact'),
    path('result/', views.search_result_view, name='search_result'),
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('dashboard/employer/job/<int:id>/applicants/', views.all_applicants_view, name='applicants'),
    path('dashboard/employer/job/edit/<int:id>', views.job_edit_view, name='edit-job'),
    path('dashboard/employer/applicant/<int:id>/<int:idjob>', views.applicant_details_view, name='applicant-details'),
    path('dashboard/employer/close/<int:id>/', views.make_complete_job_view, name='complete'),
    path('dashboard/employer/delete/<int:id>/', views.delete_job_view, name='delete'),
    path('dashboard/employee/delete-bookmark/<int:id>/', views.delete_bookmark_view, name='delete-bookmark'),


]

project-config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from .views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/',user_logIn,name="login"),
    path('employee/register',employee_registration, name='employee-registration'),
    path('employer/register',employer_registration, name='employer-registration'),
    path('profile/edit/<int:id>/', employee_edit_profile, name='edit-profile'),
    path('logout/', user_logOut, name='logout'),
    path('', include('jobapp.urls')),
    path('cvbuilder/', include('cvbuilder.urls')),
    
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobapp/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse
import os
User = get_user_model()


from ckeditor.fields import RichTextField
from taggit.managers import TaggableManager


JOB_TYPE = (
    ('1', "Full time"),
    ('2', "Part time"),
    ('3', "Internship"),
)
def get_pdf_path(instance, filename):
    return os.path.join('pdfs', str(instance.id), filename)

class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name
    

class Job(models.Model):

    user = models.ForeignKey(User, related_name='User', on_delete=models.CASCADE) 
    title = models.CharField(max_length=300)
    description = RichTextField()
    tags = TaggableManager()
    location = models.CharField(max_length=300)
    job_type = models.CharField(choices=JOB_TYPE, max_length=1)
    category = models.ForeignKey(Category,related_name='Category', on_delete=models.CASCADE)
    salary = models.CharField(max_length=30, blank=True)
    company_name = models.CharField(max_length=300)
    company_description = RichTextField(blank=True, null=True)
    url = models.URLField(max_length=200)
    last_date = models.DateField()
    is_published = models.BooleanField(default=False)
    is_closed = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.title

 

class Applicant(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now=True, auto_now_add=False)
    pdf = models.FileField(upload_to=get_pdf_path,null=True)


    def __str__(self):
        return self.job.title


  

class BookmarkJob(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now=True, auto_now_add=False)


    def __str__(self):
        return self.job.title

cvbuilder/forms.py
from .models import Experience, Resume
from django import forms
from .widgets import CustomClearableFileInput
from ckeditor.widgets import CKEditorWidget
from .models import User
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm


class ResumeForm(forms.ModelForm):
    image = forms.ImageField(required=False, widget=CustomClearableFileInput())

    class Meta:
        model = Resume
        fields = ['image', 'name', 'email', 'telephone', 'linkedin', 'github',
                  'website', 'description', 'career_summary', 'template']
        widgets = {
            'career_summary': CKEditorWidget(config_name='CVBuilder_Config')
        }


class ExperienceForm(forms.ModelForm):
    class Meta:
        model = Experience
        fields = ['title', 'company', 'duration', 'text', 'tech']
        widgets = {
            'text': CKEditorWidget(config_name='CVBuilder_Config'),
        }

cvbuilder/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View
from xhtml2pdf import pisa 
from django.http import HttpResponse
from django.template.loader import get_template 
from django.template import Context 
from .mixins import LoginRequiredMixin
from .models import (Education, Resume, Experience,
                     Skill, Language, Achievement, Publication)
from .forms import ResumeForm, ExperienceForm
from django.contrib import messages
from io import StringIO,BytesIO
from django.conf import settings
from django.urls import reverse
from .models import User
from .mixins import (OwnerResumeUpdateView, OwnerResumeCreateView,
                     OwnerResumeDeleteView, SaveModelOrderMixin)
from wkhtmltopdf.views import PDFTemplateView


# ---- DOWNLOAD AS PDF ---- #

def PDFView(request):
    def get_template_name_color():
        template_name = 'cvbuilder/resumes/default.html'
        resume = Resume.objects.get(user=request.user)
        color = 'blue'
        template = resume.template
        if not template is None:
            if not template.name == "":
                template_name = 'cvbuilder/resumes/' + template.name.split(" ")[0].lower() + '.html'
                color = template.name.split(" ")[1].lower()
        return {'template_name': template_name,'color': color}
    template = get_template(get_template_name_color()['template_name']) 
    resume = Resume.objects.get(user=request.user)
    context = {
            'resume': resume,
            'experiences': resume.experiences.all().order_by('order'),
            'skills': resume.skills.all().order_by('order'),
            'educations': resume.educations.all().order_by('order'),
            'languages': resume.languages.all().order_by('order'),
            'achievements': resume.achievements.all().order_by('order'),
            'publications': resume.publications.all().order_by('order'),
            'color': get_template_name_color()['color'],
            'pagesize':'A4'}
        
    html = template.render(context)
    print(html)
    pdf_file_object = BytesIO()
    result = StringIO() 
    pdf = pisa.pisaDocument(BytesIO(html.encode("UTF-8")),dest=pdf_file_object,
            encoding='UTF-8',css="/cvbuilder/default_blue.css") 
    if not pdf.err: 
         return HttpResponse(pdf_file_object.getvalue(), content_type='application/pdf') 
    else: return HttpResponse('Errors')


# ---- MAIN PAGE - EDIT OF DETAILS ---- #

class MainPage(LoginRequiredMixin, View):
    template_name = 'cvbuilder/0_mainpage.html'

    def get(self, request):
        try:
            resume = Resume.objects.get(user=request.user)
        except Resume.DoesNotExist:
            resume = Resume(user=request.user, name=request.user.username)
            resume.save()

        ctx = {
            'resume': resume,
            'form': ResumeForm(instance=resume),
            'experiences': resume.experiences.all().order_by('order'),
            'skills': resume.skills.all().order_by('order'),
            'educations': resume.educations.all().order_by('order'),
            'languages': resume.languages.all().order_by('order'),
            'achievements': resume.achievements.all().order_by('order'),
            'publications': resume.publications.all().order_by('order'),
        }
        return render(request, self.template_name, ctx)

    def post(self, request):
        resume = Resume.objects.get(user=request.user)
        form = ResumeForm(request.POST, request.FILES, instance=resume)
        if not form.is_valid: return render(request, self.template_name, {'form': form})
        form.save()
        messages.info(request, 'Resume information saved')
        return redirect(reverse('cvbuilder:MainPage'))


# --- RESUME VIEW AS HTML ---- #

class ResumePreview(LoginRequiredMixin, View):
    def get(self, request):
        userr = User.objects.get(email=request.user.email)
        resume = Resume.objects.get(user=userr)
        template = resume.template

        # Default Template Values
        template_name = 'cvbuilder/resumes/default.html'
        color = 'blue'

        if not template is None:
            if not template.name == "":
                template_name = 'cvbuilder/resumes/' + template.name.split(" ")[0].lower() + '.html'
                color = template.name.split(" ")[1]

        if not resume.user == request.user: return redirect(reverse('pages:NoAccess'))
        ctx = {
            'resume': resume,
            'experiences': resume.experiences.all().order_by('order'),
            'skills': resume.skills.all().order_by('order'),
            'educations': resume.educations.all().order_by('order'),
            'languages': resume.languages.all().order_by('order'),
            'achievements': resume.achievements.all().order_by('order'),
            'publications': resume.publications.all().order_by('order'),
            'color': color.lower(),
        }
        return render(request, template_name, ctx)


# --- SHARED RESUME VIEW AS HTML ---- #

class SharedResumePreview(View):
    def get(self, request, code):
        resume = Resume.objects.get(code=code)
        template = resume.template

        # Default Template Values
        template_name = 'cvbuilder/resumes/default.html'
        color = 'blue'

        if not template is None:
            if not template.name == "":
                template_name = 'cvbuilder/resumes/' + template.name.split(" ")[0].lower() + '.html'
                color = template.name.split(" ")[1]

        ctx = {
            'resume': resume,
            'experiences': resume.experiences.all().order_by('order'),
            'skills': resume.skills.all().order_by('order'),
            'educations': resume.educations.all().order_by('order'),
            'languages': resume.languages.all().order_by('order'),
            'achievements': resume.achievements.all().order_by('order'),
            'publications': resume.publications.all().order_by('order'),
            'shared_view': 1,
            'color': color.lower(),
        }

        return render(request, template_name, ctx)


#### --------------------- CRUD VIEWS --------------------- ####

# ---- Experience CRUD --- #

class SaveExperienceOrdering(SaveModelOrderMixin):
    model = Experience


class CreateExperience(OwnerResumeCreateView):
    model = Experience
    form_class = ExperienceForm
    template_name = 'cvbuilder/crud_experience.html'
    success_url = reverse_lazy('cvbuilder:MainPage')


class UpdateExperience(OwnerResumeUpdateView):
    model = Experience
    form_class = ExperienceForm
    template_name = 'cvbuilder/crud_experience.html'
    success_url = reverse_lazy('cvbuilder:MainPage')


class DeleteExperience(OwnerResumeDeleteView):
    model = Experience
    success_url = reverse_lazy('cvbuilder:MainPage')


# ---- Skills CRUD --- #

class SaveSkillsOrder(SaveModelOrderMixin):
    model = Skill


class CreateSkill(OwnerResumeCreateView):
    model = Skill
    fields = ['title']
    template_name = 'cvbuilder/crud_skill.html'
    success_url = reverse_lazy('cvbuilder:MainPage')


class DeleteSkill(OwnerResumeDeleteView):
    model = Skill
    success_url = reverse_lazy('cvbuilder:MainPage')


# ---- Education CRUD --- #

class SaveEducationOrder(SaveModelOrderMixin):
    model = Education


class CreateEducation(OwnerResumeCreateView):
    model = Education
    fields = ['title', 'description', 'duration']
    template_name = 'cvbuilder/crud_education.html'
    success_url = reverse_lazy('cvbuilder:MainPage')


class UpdateEducation(OwnerResumeUpdateView):
    model = Education
    fields = ['title', 'description', 'duration']
    template_name = 'cvbuilder/crud_education.html'
    success_url = reverse_lazy('cvbuilder:MainPage')


class DeleteEducation(OwnerResumeDeleteView):
    model = Education
    success_url = reverse_lazy('cvbuilder:MainPage')


# ---- Language CRUD --- #

class SaveLanguageOrder(SaveModelOrderMixin):
    model = Language


class CreateLanguage(OwnerResumeCreateView):
    model = Language
    fields = ['title', 'level']
    template_name = 'cvbuilder/crud_language.html'
    success_url = reverse_lazy('cvbuilder:MainPage')


class UpdateLanguage(OwnerResumeUpdateView):
    model = Language
    fields = ['title', 'level']
    template_name = 'cvbuilder/crud_language.html'
    success_url = reverse_lazy('cvbuilder:MainPage')


class DeleteLanguage(OwnerResumeDeleteView):
    model = Language
    success_url = reverse_lazy('cvbuilder:MainPage')


# ---- Achievement CRUD --- #

class SaveAchievementOrder(SaveModelOrderMixin):
    model = Achievement


class CreateAchievement(OwnerResumeCreateView):
    model = Achievement
    fields = ['title', 'description']
    template_name = 'cvbuilder/crud_achievement.html'
    success_url = reverse_lazy('cvbuilder:MainPage')


class UpdateAchievement(OwnerResumeUpdateView):
    model = Achievement
    fields = ['title', 'description']
    template_name = 'cvbuilder/crud_achievement.html'
    success_url = reverse_lazy('cvbuilder:MainPage')


class DeleteAchievement(OwnerResumeDeleteView):
    model = Achievement
    success_url = reverse_lazy('cvbuilder:MainPage')


# ---- Publication CRUD --- #

class SavePublicationOrder(SaveModelOrderMixin):
    model = Publication


class CreatePublication(OwnerResumeCreateView):
    model = Publication
    fields = ['title', 'description']
    template_name = 'cvbuilder/crud_publication.html'
    success_url = reverse_lazy('cvbuilder:MainPage')


class UpdatePublication(OwnerResumeUpdateView):
    model = Publication
    fields = ['title', 'description']
    template_name = 'cvbuilder/crud_publication.html'
    success_url = reverse_lazy('cvbuilder:MainPage')


class DeletePublication(OwnerResumeDeleteView):
    model = Publication
    success_url = reverse_lazy('cvbuilder:MainPage')

cvbuilder/templates/jobapp/all-applicants.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section class="section-hero overlay inner-page bg-image" style="background-image: url('{% static 'images/hero_1.jpg' %}');"
    id="home-section">
    <div class="container">
        <div class="row">
            <div class="col-md-7">
                <h1 class="text-white font-weight-bold">All Applicants </h1>
                <div class="custom-breadcrumbs">
                    <a href="{% url 'jobapp:home' %}">Home</a> <span class="mx-2 slash">/</span>
                    <a href="{% url 'jobapp:dashboard' %}">Dashboard</a> <span class="mx-2 slash">/</span>
                    <span class="text-white"><strong>All Applicants </strong></span>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="site-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 mb-5">
                <div class="card">
                    <h5 class="card-header text-center mb-5"> All Applicants </h5>
                    <div class="table-responsive">
                        <table class="table text-center">
                            <thead class="thead-dark">
                                <tr>
                                    <th>Name</th>
                                    <th>Job Title</th>
                                    <th>Applied Date</th>
                                    <th>View </th>
                        
                                </tr>
                            </thead>
                            <tbody>
                                {% for applicant in all_applicants %}
                        {{ applicant.get_total_applicant }}

                                <tr>
                                    <td class="text-center"><a href="">{{ applicant.user.get_full_name }}</a></td     >
                                    <td>{{ applicant.job.title }}</td>
                                    <td>{{ applicant.timestamp }}</td>
                                    <td>
                                        <a class="btn btn-info btn-sm" href="{% url 'jobapp:applicant-details' applicant.user.id idjob %}"
                                                role="button">
                                            Click
                                        </a>
                                    </td>

                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

</section>

{% endblock %}

cvbuilder/templates/jobapp/dashboard.html
{% extends 'base.html' %}
{% load static %}
{% load get_total_applicant %}
{% block content %}

<section class="section-hero overlay inner-page bg-image"
    style="background-image: url('{% static 'images/hero_1.jpg' %}');" id="home-section">
    <div class="container">
        <div class="row">
            <div class="col-md-7">
                <h1 class="text-white font-weight-bold">Dashboard</h1>
                <div class="custom-breadcrumbs">
                    <a href="{% url 'jobapp:home' %}">Home</a> <span class="mx-2 slash">/</span>
                    <a href="{% url 'jobapp:job-list' %}">Job</a> <span class="mx-2 slash">/</span>
                    <span class="text-white"><strong>Dashboard</strong></span>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="site-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 mb-5">
                {% include 'messages.html' %}

                <div class="card">
                    {% if user.role == "employer" %}
                    <h5 class="card-header text-center">My All Job</h5>
                    {% if jobs %}
                    <table class="table text-center mt-5">
                        <thead class="thead-dark">
                            <tr>
                                <th>Job Title</th>
                                <th>Posted Date</th>
                                <th>Date expiring</th>
                                <th>Status</th>
                                <th>Applicants</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for job in jobs %}
                            <tr id="row_{{ job.id }}">
                                <td class="text-left"><a href="{% url 'jobapp:single-job' job.id %}">{{ job.title }}</a></td>
                                <td>{{ job.timestamp | date:'M d, Y'  }}</td>
                                <td>{{ job.last_date | date:'M d, Y' }}</td>
                                <td>
                                    {% if job.is_published == True %}
                                
                                        <span class="badge badge-info">Published</span>
                                
                                    {% else %}

                                        <span class="badge badge-danger px-2">Pending</span>

                                    {% endif %}
                                
                                </td>

                                <td>

                                    {% get_total_applicant total_applicants job as is_applicant %}

                                    {% if is_applicant %}
                                    <a href="{% url 'jobapp:applicants' job.id %}">
                                        <i class="fa fa-users"></i>
                                        <span class="badge badge-success text-white">

                                       
                                            {% if is_applicant > 1 %}


                                            {% get_total_applicant total_applicants job %} Applicants

                                            {% else %}

                                            {% get_total_applicant total_applicants job %} Applicant

                                            {% endif %}

                                        </span>
                                        
                                    </a>
                                    {% endif %}

                                </td>
                                <td>
                                    <a class="btn btn-info btn-sm" href="{% url 'jobapp:edit-job' job.id %}"
                                        role="button">Edit</a>
                                    {% if job.is_published == True %}
                                        {% if job.is_closed == False %}
                                        <span id="change_job_status_{{ job.id }}">
                                            <button onclick="call_sw_alert_func('{% url 'jobapp:complete' job.id %}','{{ job.id }}', 'Once Clicked, Your Post Will Marked Completed')" class="text-white btn btn-success btn-sm" >Make Close</button>
                                        </span>
                                        {% else %}
                                        <a class="text-white btn btn-success btn-sm" 
                                        role="button">Closed</a>                                    
                                        {% endif %}
                                        {% endif %}
                                    <button onclick="call_sw_alert_func('{% url 'jobapp:delete' job.id %}','{{ job.id }}','Once Deleted, You Will Not be Able To Recover This Post!')" class="btn btn-danger btn-sm">Delete</button>
                                    </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    {% else %}
                    <p class="m-5">You have not any job yet !! <a href="{% url 'jobapp:create-job' %}">Create a new one.</a></p>
                    {% endif %}
                    {% elif user.role == "employee" %}


                    <ul class="mb-3 nav nav-tabs" id="myTab" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Bookmarked Job</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Aplied Job</a>
                        </li>
                      </ul>
                      <div class="tab-content" id="myTabContent">
                        <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                            <h5 class="card-header text-center">Bookmarked Posts</h5>
                            {% if savedjobs %}
                            <table class="table text-center mt-5">
                                <thead class="thead-dark">
                                    <tr>
                                        <th>Job Title</th>
                                        <th>Posted Date</th>
                                        <th>Date expiring</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for job in savedjobs %}
                                    <tr id="row_{{ job.id }}">
                                        <td><a href="{% url 'jobapp:single-job' job.job.id %}">{{ job.job.title }}</a></td>
                                        <td>{{ job.timestamp | date:'M d, Y'  }}</td>
                                        <td>{{ job.job.last_date | date:'M d, Y' }}</td>
                                        <td>
                                            <button onclick="call_sw_alert_func('{% url 'jobapp:delete-bookmark' job.id %}','{{ job.id }}','Once Deleted, This Post Will Remove From Your Favourite List!')" class="btn btn-danger btn-sm">Delete</button>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                            {% else %}
                            <p class="m-5">You have not any save job yet !! </p>
                            {% endif %}
                        </div>
                        <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                            <h5 class="card-header text-center">Aplied Posts</h5>
                            {% if appliedjobs %}
                            <table class="table text-center mt-5">
                                <thead class="thead-dark">
                                    <tr>
                                        <th>Job Title</th>
                                        <th>Posted Date</th>
                                        <th>Date expiring</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for job in appliedjobs %}
                                    <tr id="row_{{ job.id }}">
                                        <td><a href="{% url 'jobapp:single-job' job.job.id %}">{{ job.job.title }}</a></td>
                                        <td>{{ job.timestamp | date:'M d, Y'  }}</td>
                                        <td>{{ job.job.last_date | date:'M d, Y' }}</td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                            {% else %}
                            <p class="m-5">You have not any applied job yet !! </p>
                            {% endif %}
                        </div>
                        
                      </div>

                    {% endif %}

                </div>
            </div>
        </div>

    </div>
    </div>
</section>
{% endblock %}

{% block extra_scripts %}
    <script src="{% static 'js/sweet-alert.js' %}"></script>
    <script src="{% static 'js/sweet-alert-ajax.js' %}"></script>
{% endblock %}

cvbuilder/templates/jobapp/paginator.html
{% if page_obj.has_other_pages %}
<div class="row pagination-wrap">
  <div class="col-md-6 text-center text-md-left mb-4 mb-md-0">
    <span id="page_navigator">Showing {{ page_obj.number }} of {{ page_obj.paginator.num_pages }} Pages</span>
  </div>
  <div class="col-md-6 text-center text-md-right">
    <div class="custom-pagination ml-auto">
      
      <span id="prev_page">
      {% if page_obj.has_previous %}
      <a id="ajax_paginator" href="?page={{ page_obj.previous_page_number }}" class="prev">Prev</a>
      {% endif %}
    </span>
      <span id="page_no">
        <div class="d-inline-block">
          {% for i in page_obj.paginator.page_range %}
          {% if page_obj.number == i %}
          <a id="ajax_paginator" class="ajax_paginator_{{ i }} active" href="?page={{ i }}">{{ i }}</a>

          {% else %}
          <a class="ajax_paginator_{{ i }}" id="ajax_paginator" href="?page={{ i }}">{{ i }}</a>
          {% endif %}
          {% endfor %}
        </div>
      </span>
      {% if page_obj.has_next %}
      <span id="next_page">
        <a id="ajax_paginator" class="next" href="?page={{ page_obj.next_page_number }}">Next</a>
      </span>
      {% endif %}
    
    </div>
  </div>
</div>
{% endif %}